export const ROLES = {
  PATRON: 'PATRON',
  GERANT: 'GERANT',
  MAGASINIER: 'MAGASINIER',
  CAISSIER: 'CAISSIER',
  COMPTABLE: 'COMPTABLE',
  COMMERCIAL: 'COMMERCIAL',
  MANUTENTIONNAIRE: 'MANUTENTIONNAIRE',
};

export const PERMISSIONS = {
  TENANT_ALL_DEPOTS: [ROLES.PATRON, ROLES.COMPTABLE],
  STOCK_READ: [ROLES.PATRON, ROLES.GERANT, ROLES.MAGASINIER],
  STOCK_WRITE: [ROLES.PATRON, ROLES.GERANT, ROLES.MAGASINIER],
  SALES_READ: [ROLES.PATRON, ROLES.GERANT, ROLES.CAISSIER, ROLES.COMPTABLE],
  SALES_WRITE: [ROLES.PATRON, ROLES.GERANT, ROLES.CAISSIER],
  FINANCE_READ: [ROLES.PATRON, ROLES.GERANT, ROLES.COMPTABLE],
  FINANCE_WRITE: [ROLES.PATRON, ROLES.GERANT, ROLES.CAISSIER],
  EMPLOYEES_READ: [ROLES.PATRON, ROLES.GERANT],
  EMPLOYEES_WRITE: [ROLES.PATRON, ROLES.GERANT],
  DEPOTS_READ: [ROLES.PATRON, ROLES.GERANT, ROLES.COMPTABLE],
  DEPOTS_WRITE: [ROLES.PATRON],
  CUSTOMER_ORDERS: [ROLES.PATRON, ROLES.GERANT, ROLES.COMMERCIAL],
};

export function hasRole(role, allowedRoles = []) {
  if (!role) return false;
  return allowedRoles.includes(role);
}

export function filterByRole(items, role) {
  return items.filter((item) => !item.roles || hasRole(role, item.roles));
}
