const BUSINESS_LABELS = {
  DEPOT_BOISSONS: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Produit/Boisson',
      stock: 'Stock boissons',
      vente: 'Vente',
      livraison: 'Livraison',
      transport: 'Tricycle',
      chauffeur: 'Chauffeur',
      tournee: 'Tournée',
      consigne: 'Consigne',
      casier: 'Casier',
      commande: 'Commande fournisseur',
      facture: 'Facture',
      depot: 'Dépôt',
      rapport: 'Rapport',
      categorie: 'Catégorie boisson',
      dlc: 'DLC & Lots',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Consignes',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un produit',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  PHARMACIE: {
    entity: {
      client: 'Patient',
      fournisseur: 'Laboratoire',
      produit: 'Médicament',
      stock: 'Stock médicaments',
      vente: 'Vente',
      livraison: 'Réception lot',
      transport: 'Livraison',
      chauffeur: 'Livreur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande laboratoire',
      facture: 'Ordonnance',
      depot: 'Pharmacie',
      rapport: 'Rapport',
      categorie: 'Famille médicament',
      dlc: 'Expirations & Lots',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Réceptions',
      consigne: 'Retours',
      client: 'Patients',
      fournisseur: 'Laboratoires',
      caisse: 'Caisse',
      facture: 'Ordonnances',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un médicament',
      add_client: 'Nouveau patient',
      add_fournisseur: 'Nouveau laboratoire',
      add_livraison: 'Nouvelle réception',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  RESTAURANT: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Plat',
      stock: 'Stock cuisine',
      vente: 'Vente',
      livraison: 'Livraison',
      transport: 'Livreur',
      chauffeur: 'Livreur',
      tournee: 'Service',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Addition',
      depot: 'Restaurant',
      rapport: 'Rapport',
      categorie: 'Catégorie plat',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock cuisine',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Consignes',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Additions',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Services',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un plat',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouveau service',
      new_vente: 'Nouvelle vente',
    },
  },

  HOTEL: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Article',
      stock: 'Stock hôtel',
      vente: 'Vente',
      livraison: 'Livraison',
      transport: 'Navette',
      chauffeur: 'Chauffeur',
      tournee: 'Service',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Facture',
      depot: 'Hôtel',
      rapport: 'Rapport',
      categorie: 'Catégorie',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Consignes',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Services',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un article',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouveau service',
      new_vente: 'Nouvelle vente',
    },
  },

  ELEVAGE: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur aliments',
      produit: 'Animal',
      stock: 'Stock aliments',
      vente: 'Vente',
      livraison: 'Réception',
      transport: 'Véhicule',
      chauffeur: 'Conducteur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Enclos',
      commande: 'Commande aliments',
      facture: 'Facture',
      depot: 'Ferme',
      rapport: 'Rapport',
      categorie: 'Espèce',
      dlc: 'Expirations aliments',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock aliments',
      vente: 'Ventes',
      livraison: 'Réceptions',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un animal',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle réception',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  BOUTIQUE: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Article',
      stock: 'Stock boutique',
      vente: 'Vente',
      livraison: 'Livraison',
      transport: 'Livraison',
      chauffeur: 'Livreur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Facture',
      depot: 'Boutique',
      rapport: 'Rapport',
      categorie: 'Catégorie',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un article',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  QUINCAILLERIE: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Matériau',
      stock: 'Stock matériaux',
      vente: 'Vente',
      livraison: 'Livraison chantier',
      transport: 'Camion',
      chauffeur: 'Chauffeur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Facture',
      depot: 'Dépôt',
      rapport: 'Rapport',
      categorie: 'Catégorie',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock matériaux',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un matériau',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  TELEPHONIE: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Téléphone',
      stock: 'Stock téléphones',
      vente: 'Vente',
      livraison: 'Livraison',
      transport: 'Livraison',
      chauffeur: 'Livreur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Facture',
      depot: 'Boutique',
      rapport: 'Rapport',
      categorie: 'Marque',
      dlc: 'Garanties',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un téléphone',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  SUPERMARCHE: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Produit',
      stock: 'Stock rayon',
      vente: 'Vente',
      livraison: 'Réception',
      transport: 'Livraison',
      chauffeur: 'Livreur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Ticket de caisse',
      depot: 'Magasin',
      rapport: 'Rapport',
      categorie: 'Famille',
      dlc: 'DLC',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Réceptions',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Tickets',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un produit',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle réception',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  CIMENT_BTP: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Matériau',
      stock: 'Stock dépôt',
      vente: 'Vente',
      livraison: 'Livraison chantier',
      transport: 'Camion benne',
      chauffeur: 'Chauffeur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Facture',
      depot: 'Dépôt',
      rapport: 'Rapport',
      categorie: 'Type',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un matériau',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  PRESSING: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur produits',
      produit: 'Service',
      stock: 'Stock produits',
      vente: 'Vente',
      livraison: 'Livraison',
      transport: 'Livraison',
      chauffeur: 'Livreur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Ticket',
      depot: 'Magasin',
      rapport: 'Rapport',
      categorie: 'Type service',
      dlc: 'Délais',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Tickets',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un service',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouveau ticket',
    },
  },

  GARAGE_AUTOMOBILE: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur pièces',
      produit: 'Pièce détachée',
      stock: 'Stock pièces',
      vente: 'Vente',
      livraison: 'Réception pièce',
      transport: 'Dépanneuse',
      chauffeur: 'Mécanicien',
      tournee: 'Intervention',
      consigne: 'Retour pièce',
      casier: 'Casier',
      commande: 'Commande pièce',
      facture: 'Facture réparation',
      depot: 'Garage',
      rapport: 'Rapport',
      categorie: 'Type pièce',
      dlc: 'Garantie',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock pièces',
      vente: 'Ventes',
      livraison: 'Réceptions',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Interventions',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter une pièce',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle réception',
      add_tournee: 'Nouvelle intervention',
      new_vente: 'Nouvelle facture',
    },
  },

  SALON_BEAUTE: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Produit',
      stock: 'Stock produits',
      vente: 'Vente',
      livraison: 'Livraison',
      transport: 'Livraison',
      chauffeur: 'Livreur',
      tournee: 'Service',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Ticket',
      depot: 'Salon',
      rapport: 'Rapport',
      categorie: 'Type prestation',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock produits',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Tickets',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Services',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un produit',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouveau service',
      new_vente: 'Nouvelle vente',
    },
  },

  PARFUMERIE: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Parfum / Cosmétique',
      stock: 'Stock',
      vente: 'Vente',
      livraison: 'Livraison',
      transport: 'Livraison',
      chauffeur: 'Livreur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Facture',
      depot: 'Boutique',
      rapport: 'Rapport',
      categorie: 'Famille',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un produit',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  BOULANGERIE: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Pain / Viennoiserie',
      stock: 'Stock matières',
      vente: 'Vente',
      livraison: 'Livraison',
      transport: 'Livraison',
      chauffeur: 'Livreur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Panier',
      commande: 'Commande',
      facture: 'Ticket',
      depot: 'Boulangerie',
      rapport: 'Rapport',
      categorie: 'Famille',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Tickets',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un produit',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  GLACIER_SNACK: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Parfum / Snack',
      stock: 'Stock',
      vente: 'Vente',
      livraison: 'Livraison',
      transport: 'Livraison',
      chauffeur: 'Livreur',
      tournee: 'Service',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Ticket',
      depot: 'Glacier',
      rapport: 'Rapport',
      categorie: 'Famille',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Livraisons',
      consigne: 'Consignes',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Tickets',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Services',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un parfum',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouveau service',
      new_vente: 'Nouvelle vente',
    },
  },

  LIBRAIRIE: {
    entity: {
      client: 'Client',
      fournisseur: 'Éditeur',
      produit: 'Livre',
      stock: 'Stock librairie',
      vente: 'Vente',
      livraison: 'Réception',
      transport: 'Livraison',
      chauffeur: 'Livreur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande spéciale',
      facture: 'Ticket',
      depot: 'Librairie',
      rapport: 'Rapport',
      categorie: 'Genre',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Ventes',
      livraison: 'Réceptions',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Éditeurs',
      caisse: 'Caisse',
      facture: 'Tickets',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un livre',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouvel éditeur',
      add_livraison: 'Nouvelle réception',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle vente',
    },
  },

  CLINIQUE: {
    entity: {
      client: 'Patient',
      fournisseur: 'Fournisseur médical',
      produit: 'Médicament',
      stock: 'Stock pharmacie',
      vente: 'Consultation',
      livraison: 'Réception',
      transport: 'Ambulance',
      chauffeur: 'Chauffeur',
      tournee: 'Visite',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Facture soins',
      depot: 'Clinique',
      rapport: 'Rapport médical',
      categorie: 'Spécialité',
      dlc: 'Expirations',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock pharmacie',
      vente: 'Consultations',
      livraison: 'Réceptions',
      consigne: 'Retours',
      client: 'Patients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Visites',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un médicament',
      add_client: 'Nouveau patient',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle réception',
      add_tournee: 'Nouvelle visite',
      new_vente: 'Nouvelle consultation',
    },
  },

  TRANSPORT: {
    entity: {
      client: 'Client',
      fournisseur: 'Fournisseur',
      produit: 'Colis',
      stock: 'Stock',
      vente: 'Expédition',
      livraison: 'Livraison colis',
      transport: 'Camion',
      chauffeur: 'Chauffeur',
      tournee: 'Tournée',
      consigne: 'Retour',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Facture',
      depot: 'Agence',
      rapport: 'Rapport',
      categorie: 'Type',
      dlc: 'Garantie',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Stock',
      vente: 'Expéditions',
      livraison: 'Livraisons',
      consigne: 'Retours',
      client: 'Clients',
      fournisseur: 'Fournisseurs',
      caisse: 'Caisse',
      facture: 'Factures',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Tournées',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un colis',
      add_client: 'Nouveau client',
      add_fournisseur: 'Nouveau fournisseur',
      add_livraison: 'Nouvelle livraison',
      add_tournee: 'Nouvelle tournée',
      new_vente: 'Nouvelle expédition',
    },
  },

  IMMOBILIER: {
    entity: {
      client: 'Locataire',
      fournisseur: 'Prestataire',
      produit: 'Bien',
      stock: 'Portefeuille',
      vente: 'Location',
      livraison: 'Livraison',
      transport: 'Véhicule',
      chauffeur: 'Chauffeur',
      tournee: 'Visite',
      consigne: 'Caution',
      casier: 'Casier',
      commande: 'Commande',
      facture: 'Quittance',
      depot: 'Agence',
      rapport: 'Rapport',
      categorie: 'Type bien',
      dlc: 'Échéance',
    },
    menu: {
      dashboard: 'Tableau de bord',
      stock: 'Portefeuille',
      vente: 'Locations',
      livraison: 'Livraisons',
      consigne: 'Caution',
      client: 'Locataires',
      fournisseur: 'Prestataires',
      caisse: 'Caisse',
      facture: 'Quittances',
      rapport: 'Rapports',
      depense: 'Dépenses',
      tournee: 'Visites',
      commande: 'Commandes',
    },
    action: {
      add_product: 'Ajouter un bien',
      add_client: 'Nouveau locataire',
      add_fournisseur: 'Nouveau prestataire',
      add_livraison: 'Nouveau contrat',
      add_tournee: 'Nouvelle visite',
      new_vente: 'Nouvelle location',
    },
  },
};

export function getBusinessLabels(metier) {
  const defaultMetier = BUSINESS_LABELS.DEPOT_BOISSONS;
  const metierLabels = BUSINESS_LABELS[metier];
  if (!metierLabels) return defaultMetier;
  return {
    entity: { ...defaultMetier.entity, ...metierLabels.entity },
    menu: { ...defaultMetier.menu, ...metierLabels.menu },
    action: { ...defaultMetier.action, ...metierLabels.action },
  };
}
