import { useState, useEffect, useCallback } from 'react';
import api from '../../api';
import FormModal from '../../shared/components/forms/FormModal';
import ConfirmModal from '../../shared/components/forms/ConfirmModal';
import { useTenant } from '../../hooks/useTenant';

const ROLE_OPTIONS = [
  { value: 'GERANT', label: 'Gérant' }, { value: 'CAISSIER', label: 'Caissier' },
  { value: 'MAGASINIER', label: 'Magasinier' }, { value: 'COMMERCIAL', label: 'Commercial' },
  { value: 'COMPTABLE', label: 'Comptable' }, { value: 'ADMIN', label: 'Administrateur' },
];
const EMPTY_FORM = { nom: '', prenom: '', email: '', password: '', role: 'GERANT', depotId: '' };

export default function UtilisateursPage() {
  const { tenant } = useTenant();
  const [users, setUsers] = useState([]); const [depots, setDepots] = useState([]); const [loading, setLoading] = useState(true);
  const [formOpen, setFormOpen] = useState(false); const [editingUser, setEditingUser] = useState(null); const [formLoading, setFormLoading] = useState(false);
  const [form, setForm] = useState(EMPTY_FORM); const [notif, setNotif] = useState(null); const [confirmDelete, setConfirmDelete] = useState(null); const [deleting, setDeleting] = useState(false);
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const itemsPerPage = 20;
  const metier = localStorage.getItem('gestock_metier') || ''; const apiBase = metier.toLowerCase().replace(/_/g, '-');
  const showNotif = (msg, type = 'success') => { setNotif({ msg, type }); setTimeout(() => setNotif(null), 3000); };
  const load = useCallback(async () => { if (!apiBase) return; setLoading(true); try { const [u, d] = await Promise.all([api.get(`/${apiBase}/utilisateurs`), api.get(`/${apiBase}/depots`)]); setUsers(u.data?.data || u.data || []); setDepots(d.data?.data || d.data || []); } catch (err) { setUsers([]); setDepots([]); showNotif(err.response?.data?.message || 'Impossible de charger les données', 'error'); } finally { setLoading(false); } }, [apiBase]);
  useEffect(() => { load(); }, [load]);
  const openCreate = () => { setEditingUser(null); setForm(EMPTY_FORM); setFormOpen(true); };
  const openEdit = (u) => { setEditingUser(u); setForm({ nom: u.nom || '', prenom: u.prenom || '', email: u.email || '', password: '', role: u.role || 'GERANT', depotId: u.depotId || '' }); setFormOpen(true); };
  const setF = f => e => setForm(prev => ({ ...prev, [f]: e.target.value }));
  const handleSubmit = async e => { e.preventDefault(); if (!apiBase) return showNotif('Métier actif invalide', 'error'); if (!form.nom.trim() || !form.email.trim()) return showNotif('Nom et email sont requis', 'error'); if (!editingUser && !form.password) return showNotif('Le mot de passe est requis', 'error'); if (form.password && form.password.length < 6) return showNotif('Le mot de passe doit contenir au moins 6 caractères', 'error'); setFormLoading(true); try { if (editingUser) { const payload = { nom: form.nom.trim(), prenom: form.prenom.trim() || undefined, role: form.role, depotId: form.depotId || undefined }; if (form.password) payload.password = form.password; await api.patch(`/${apiBase}/utilisateurs/${encodeURIComponent(editingUser.id)}`, payload); } else { await api.post(`/${apiBase}/utilisateurs`, { ...form, nom: form.nom.trim(), prenom: form.prenom.trim() || undefined, depotId: form.depotId || undefined, ...(tenant?.id ? { tenantId: tenant.id } : {}) }); } setFormOpen(false); setEditingUser(null); showNotif(editingUser ? 'Utilisateur modifié ✓' : 'Utilisateur créé ✓'); await load(); } catch (err) { showNotif(err.response?.data?.message || (editingUser ? 'Erreur modification' : 'Erreur création'), 'error'); } finally { setFormLoading(false); } };
  const handleDelete = async () => { if (!confirmDelete || !apiBase) return; setDeleting(true); try { await api.delete(`/${apiBase}/utilisateurs/${encodeURIComponent(confirmDelete.id)}`); setConfirmDelete(null); showNotif('Utilisateur supprimé'); await load(); } catch (err) { showNotif(err.response?.data?.message || 'Erreur suppression', 'error'); } finally { setDeleting(false); } };
  const getDepotNom = id => depots.find(d => d.id === id)?.nom || '—';
  const filtre = users.filter(u => { const q = search.toLowerCase().trim(); return !q || [u.nom, u.prenom, u.email, u.role].some(v => v?.toLowerCase().includes(q)); });
  const totalPages = Math.ceil(filtre.length / itemsPerPage); const paginated = filtre.slice((page - 1) * itemsPerPage, page * itemsPerPage); const goToPage = p => setPage(Math.max(1, Math.min(p, totalPages || 1)));
  return <div className="p-6">
    {notif && <div className={`fixed top-4 right-4 z-[70] px-6 py-3 rounded-xl shadow-2xl text-white font-bold text-sm ${notif.type === 'error' ? 'bg-red-600' : 'bg-emerald-600'}`}>{notif.msg}</div>}
    <div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-black text-white">👤 Gestion des Utilisateurs</h1><p className="text-slate-400 text-sm mt-1">{filtre.length} utilisateur{filtre.length !== 1 ? 's' : ''}</p></div><button onClick={openCreate} className="bg-amber-500 hover:bg-amber-400 text-slate-900 font-bold px-5 py-2.5 rounded-xl text-sm">+ Nouvel Utilisateur</button></div>
    <input type="text" placeholder="🔍 Rechercher..." value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} className="bg-slate-800 border border-slate-700 text-white rounded-xl px-4 py-2 text-sm outline-none w-56 mb-6" />
    {loading ? <div className="flex items-center justify-center py-20"><div className="w-8 h-8 border-4 border-amber-500 border-t-transparent rounded-full animate-spin" /></div> : <div className="bg-slate-800/60 border border-slate-700/50 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-900/50"><tr className="text-slate-500 text-xs font-bold uppercase tracking-widest"><th className="text-left px-5 py-4">Nom</th><th className="text-left px-5 py-4">Prénom</th><th className="text-left px-5 py-4">Email</th><th className="text-left px-5 py-4">Poste</th><th className="text-left px-5 py-4">Dépôt</th><th className="text-center px-5 py-4">Actions</th></tr></thead><tbody className="divide-y divide-slate-700/50">{paginated.length === 0 ? <tr><td colSpan={6} className="text-center py-16 text-slate-500">Aucun utilisateur</td></tr> : paginated.map(u => <tr key={u.id} className="hover:bg-slate-700/20"><td className="px-5 py-3 text-white font-semibold text-sm">{u.nom || '—'}</td><td className="px-5 py-3 text-slate-300 text-sm">{u.prenom || '—'}</td><td className="px-5 py-3 text-slate-300 text-sm">{u.email}</td><td className="px-5 py-3"><span className="text-xs font-bold text-amber-400 bg-amber-500/10 px-2 py-1 rounded-full">{u.role}</span></td><td className="px-5 py-3 text-slate-400 text-sm">{getDepotNom(u.depotId)}</td><td className="px-5 py-3 text-center"><div className="flex justify-center gap-1"><button onClick={() => openEdit(u)} title="Modifier" className="text-blue-400 hover:bg-blue-500/20 p-1.5 rounded-lg">✏️</button><button onClick={() => setConfirmDelete(u)} title="Supprimer" className="text-red-400 hover:bg-red-500/20 p-1.5 rounded-lg">🗑️</button></div></td></tr>)}</tbody></table></div>{totalPages > 1 && <div className="flex items-center justify-between px-5 py-4 border-t border-slate-700/50"><span className="text-slate-400 text-xs">Page {page}/{totalPages}</span><div className="flex gap-1"><button onClick={() => goToPage(page - 1)} disabled={page === 1} className="px-3 py-1.5 rounded-lg bg-slate-800 text-slate-400 disabled:opacity-30">◀</button>{Array.from({ length: Math.min(totalPages, 5) }, (_, i) => { const start = Math.max(1, page - 2); const p = start + i; return p <= totalPages ? <button key={p} onClick={() => goToPage(p)} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${page === p ? 'bg-amber-500 text-white' : 'bg-slate-800 text-slate-400'}`}>{p}</button> : null; })}<button onClick={() => goToPage(page + 1)} disabled={page === totalPages} className="px-3 py-1.5 rounded-lg bg-slate-800 text-slate-400 disabled:opacity-30">▶</button></div></div>}</div>}
    <FormModal isOpen={formOpen} onClose={() => { setFormOpen(false); setEditingUser(null); }} onSubmit={handleSubmit} title={editingUser ? '✏️ Modifier l’utilisateur' : '👤 Nouvel Utilisateur'} loading={formLoading} submitLabel={editingUser ? 'Enregistrer les modifications' : "Créer l'utilisateur"} submitIcon={editingUser ? '💾' : '➕'}><div className="grid grid-cols-2 gap-4"><input required placeholder="Nom *" value={form.nom} onChange={setF('nom')} className="w-full bg-slate-800 border border-slate-600 text-white rounded-xl px-4 py-3 text-sm" /><input placeholder="Prénom" value={form.prenom} onChange={setF('prenom')} className="w-full bg-slate-800 border border-slate-600 text-white rounded-xl px-4 py-3 text-sm" /></div><input required type="email" disabled={!!editingUser} placeholder="Email *" value={form.email} onChange={setF('email')} className="w-full bg-slate-800 border border-slate-600 text-white rounded-xl px-4 py-3 text-sm mt-4 disabled:opacity-50" /><input required={!editingUser} type="password" minLength={6} placeholder={editingUser ? 'Nouveau mot de passe (optionnel)' : 'Mot de passe *'} value={form.password} onChange={setF('password')} className="w-full bg-slate-800 border border-slate-600 text-white rounded-xl px-4 py-3 text-sm mt-4" /><div className="grid grid-cols-2 gap-4 mt-4"><select value={form.role} onChange={setF('role')} className="w-full bg-slate-800 border border-slate-600 text-white rounded-xl px-4 py-3 text-sm">{ROLE_OPTIONS.map(r => <option key={r.value} value={r.value}>{r.label}</option>)}</select><select value={form.depotId} onChange={setF('depotId')} className="w-full bg-slate-800 border border-slate-600 text-white rounded-xl px-4 py-3 text-sm"><option value="">Sélectionner un dépôt</option>{depots.map(d => <option key={d.id} value={d.id}>{d.nom}</option>)}</select></div></FormModal>
    <ConfirmModal isOpen={!!confirmDelete} onConfirm={handleDelete} onCancel={() => setConfirmDelete(null)} loading={deleting} title="Supprimer l'utilisateur" message={`Supprimer « ${confirmDelete?.nom || confirmDelete?.email} » ? Cette action est irréversible.`} />
  </div>;
}
