/**
 * Catalogue des actions d'audit utilisées dans GeStock.
 * `action` reste un String en base pour rester compatible avec l'historique.
 */
export const AUDIT_ACTIONS = {
  // Stock
  ENTREE_STOCK: 'ENTREE_STOCK',
  SORTIE_STOCK: 'SORTIE_STOCK',
  AJUSTEMENT_STOCK: 'AJUSTEMENT_STOCK',
  SIGNALEMENT_AVARIE: 'SIGNALEMENT_AVARIE',
  TRANSFERT_CREE: 'TRANSFERT_CREE',
  TRANSFERT_VALIDE: 'TRANSFERT_VALIDE',
  TRANSFERT_ANNULE: 'TRANSFERT_ANNULE',

  // Ventes
  VENTE_CREEE: 'VENTE_CREEE',
  VENTE_ANNULEE: 'VENTE_ANNULEE',
  REMISE_ACCORDEE: 'REMISE_ACCORDEE',
  VALIDATION_STOCK_MAGASINIER: 'VALIDATION_STOCK_MAGASINIER',

  // Réceptions fournisseurs
  RECEPTION_CREEE: 'RECEPTION_CREEE',
  RECEPTION_VALIDEE: 'RECEPTION_VALIDEE',
  RECEPTION_ANNULEE: 'RECEPTION_ANNULEE',

  // Suppressions génériques
  SUPPRESSION_ARTICLE: 'SUPPRESSION_ARTICLE',
  SUPPRESSION_UTILISATEUR: 'SUPPRESSION_UTILISATEUR',
  SUPPRESSION_CLIENT: 'SUPPRESSION_CLIENT',

  // Utilisateurs
  UTILISATEUR_CREE: 'UTILISATEUR_CREE',
  UTILISATEUR_MODIFIE: 'UTILISATEUR_MODIFIE',
  UTILISATEUR_DESACTIVE: 'UTILISATEUR_DESACTIVE',

  // Caisse / dépenses
  DEPENSE_ENREGISTREE: 'DEPENSE_ENREGISTREE',
  DEPENSE_MODIFIEE: 'DEPENSE_MODIFIEE',
  DEPENSE_SUPPRIMEE: 'DEPENSE_SUPPRIMEE',
  CAISSE_OUVERTE: 'CAISSE_OUVERTE',
  CAISSE_FERMEE: 'CAISSE_FERMEE',
  ENTREE_CAISSE: 'ENTREE_CAISSE',
  SORTIE_CAISSE: 'SORTIE_CAISSE',

  // Fournisseurs / clients — finance
  DETTE_FOURNISSEUR_REGLEE: 'DETTE_FOURNISSEUR_REGLEE',
  DETTE_CLIENT_REGLEE: 'DETTE_CLIENT_REGLEE',

  // Inventaires
  INVENTAIRE_REALISE: 'INVENTAIRE_REALISE',

  // Authentification / sécurité du compte
  CONNEXION: 'CONNEXION',
  DECONNEXION: 'DECONNEXION',
  ECHEC_CONNEXION: 'ECHEC_CONNEXION',
  CHANGEMENT_MOT_DE_PASSE: 'CHANGEMENT_MOT_DE_PASSE',
} as const;

export type AuditActionKey = keyof typeof AUDIT_ACTIONS;
